version: '1.0'

services:
    postgres:
        image: postgres:11.13
        container_name: postgres_hw4
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=0000