CREATE TABLE IF NOT EXISTS task
(
    id          int8 generated by default as identity,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(50)  NOT NULL,
    primary key (id)
);